### ISSUE TITLE
Release not showing up on packagist

### ISSUE THREAD

**Issue by delatbabel** [thephpleague/omnipay-manual#2]
Hi Kayla et al,

I created a v2.2.0 release for this yesterday but packagist is still showing v2.1.1. Probably because this package hasn't been set to auto update.

Can someone with access to the omnipay account on packagist give it a prod please?

Del

**Comment by amacneil** [comment]
Prodded. I don't know why auto-updates aren't working though, it might be something that needs to be fixed on the github side (and I'm not an admin on this repo).

**Comment by delatbabel** [comment]
Thanks.
